spring:
  application:
    name: AnipingApp
  # 아래 datasource와 jpa가 spring 밑으로 들어가야 합니다.
  datasource:
    url: jdbc:mysql://localhost:3306/aniping?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
